package com.aspsols.cotizaciones.reportes;

import java.awt.Font;
import  java.util.Map;
import java.util.Vector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.util.Iterator;
import java.util.Hashtable;
import com.aspsolutions.jdbc.ObjectType;
import com.aspsolutions.jframework.Exceptions.RecordIdNotFoundException;
import com.aspsolutions.jframework.standar.JReportUtils;
import com.aspsolutions.jreports.server.JReport;
import com.aspsolutions.jreports.server.PresentationRules;
import com.aspsolutions.jreports.server.QueryLogic;
import com.aspsolutions.jreports.server.presentation.FormatException;
import com.aspsolutions.jreports.server.presentation.ReportEllipse;
import com.aspsolutions.jreports.server.presentation.ReportFieldPresentation;
import com.aspsolutions.jreports.server.presentation.ReportLine;
import com.aspsolutions.jreports.server.presentation.ReportMargin;
import com.aspsolutions.jreports.server.presentation.ReportRectangle;
import com.aspsolutions.jreports.server.presentation.ReportImage;
import com.aspsolutions.jreports.server.presentation.ReportRegion;
import com.aspsolutions.jreports.server.presentation.ReportRepetitiveFrame;
import com.aspsolutions.jreports.server.presentation.ReportSection;
import com.aspsolutions.jreports.server.querylogic.DataLink;
import com.aspsolutions.jreports.server.querylogic.Group;
import com.aspsolutions.jreports.server.querylogic.GroupField;
import com.aspsolutions.jreports.server.querylogic.Query;
import com.aspsolutions.jreports.server.querylogic.querycomponents.FromTables;
import com.aspsolutions.jreports.server.runtime.GroupPointer;
import com.aspsolutions.jreports.server.runtime.JReportRuntime;
import com.aspsolutions.jreports.server.runtime.QueryRecords;
import com.aspsolutions.jreports.server.runtime.ReportField;
import com.aspsolutions.jreports.server.presentation.ReportText;
import com.aspsolutions.jreports.server.presentation.ReportFrame;
import com.aspsolutions.jreports.server.presentation.ReportRoundedRectangle;
import com.aspsolutions.jframework.standar.ASPString;
import com.aspsolutions.jreports.server.querylogic.querycomponents.SelectColumns;
import com.aspsolutions.jreports.server.parameters.ParameterForm;
import com.aspsolutions.jframework.Server.DataFieldDefinition;
import com.aspsolutions.jframework.Server.GraphicsObjectServer;
import javax.swing.FocusManager;
import com.aspsolutions.jframework.standar.ASPMath;
import com.aspsolutions.jframework.Server.RecordGroupServer;
import com.aspsolutions.jframework.Server.HelpListServer;
import com.aspsolutions.jreports.server.presentation.ReportChart;
import com.aspsolutions.jframework.Server.JApplicationServer;
import com.aspsolutions.jframework.standar.ASPConverter;
import com.aspsolutions.jframework.standar.ASPSQLFunctions;
import com.aspsolutions.jframework.Utils.SqlParameter;
import com.aspsolutions.jframework.Exceptions.NoDataFoundException;
import com.aspsolutions.jframework.Exceptions.TooManyRows;
import com.aspsolutions.jframework.Exceptions.NumericOrValueException;
import com.aspsolutions.jframework.srw.SRWProgramAbort;
import com.aspsolutions.jframework.standar.ASPLogicalOperators;
import java.awt.Font;
import com.aspsolutions.jreports.server.LayoutTextVariables;
import com.aspsolutions.jframework.Server.ProcedureCallParameters;
import com.aspsolutions.jframework.standar.Utils;
import com.aspsolutions.jreports.server.presentation.PresentationFormat;
import com.aspsolutions.jreports.server.presentation.Conditions;
import com.aspsolutions.jframework.Server.ColumnSpecifications;
import com.aspsolutions.jreports.server.presentation.ReportButton;
import com.aspsolutions.jreports.server.presentation.PageNumbering;
import com.aspsolutions.jframework.Exceptions.DupValOnIndexException;
import com.aspsolutions.jreports.server.presentation.ReportAnchor;
import com.aspsolutions.jframework.standar.ASPCollection;
import com.aspsolutions.jreports.server.presentation.ChartParameter;
import com.aspsolutions.jreports.server.presentation.ChartColumn;
import static com.aspsolutions.jframework.standar.ASPConverter.*;
import static com.aspsolutions.jframework.standar.ASPLogicalOperators.*;
import static com.aspsolutions.jframework.standar.ASPMath.*;
import static com.aspsolutions.jframework.standar.ASPString.*;
import com.aspsolutions.jframework.standar.ASPAccessFile;
import com.aspsolutions.jframework.srw.SRWRunReportFailure;

public class Cotizaciones_Print_class1 extends JReportRuntime {
	
	protected QueryLogic queryLogic = new QueryLogic();
	protected Group tempGroup = new Group("GrupoTemporal");
	
	protected Query queryQUERY0 = new Query("QUERY0","MASTER","WHERE E.COT = #cot AND E.REV = #rev AND E.C_AGR = #c_agr AND E.PER = #per AND E.C_EMP = #c_emp",null,"ORDER BY D.COD"," SELECT  E.C_EMP   ,E.PER   ,E.C_AGR   ,E.COT   ,E.REV   ,E.N_IDE   ,E.COD_SUC   ,E.EMI   ,E.VEN   ,E.BRU   ,E.DES   ,E.MER   ,E.IVA   ,E.TOT   ,E.COSTOS_ADIC   ,E.TOTD   ,E.MON   ,E.TASA   ,E.C_VEN   ,E.COD_INCOTERM   , NVL (E.IDIOMA, 'ESPAÑOL' )  IDIOMA  ,E.ORIGEN   ,DESTINO   ,E.COD_EMB   ,E.ZONA   ,D.COD   ,D.UNIDAD   ,D.CAN   ,D.VEN   ,D.IVA   ,E.DESPACHO   ,E.TERMINO_PAGO   ,E.TIEMPO_ENTREGA   ,E.LUGAR_DESTINO   ,C.PER_CARGO   ,C.CARGO   ,D.NOM    FROM COT_ENC E  JOIN  COT_DET D ON E.COT = D.COT AND E.REV = D.REV AND E.C_AGR = D.C_AGR AND E.PER = D.PER AND E.C_EMP = D.C_EMP  LEFT  OUTER  JOIN  CLI_CONTACTO C ON E.ID_CONTACTO = C.ID AND E.N_IDE = C.NIT AND E.C_EMP = C.C_EMP  WHERE E.COT = #cot AND E.REV = #rev AND E.C_AGR = #c_agr AND E.PER = #per AND E.C_EMP = #c_emp",null);
	protected Query queryQUERY1 = new Query("QUERY1","DETAIL","WHERE C.TIPO_SECCION =  'PRE'",null,"ORDER BY C.ORDEN ASC"," SELECT  S.C_EMP   ,S.PER   ,S.C_AGR   ,S.COT   ,S.REV   ,S.COD_SECCION   ,S.DESCRIPCION   , NVL (S.ETIQUETA, NVL (CS.DESCRIPCION,C.NOMBRE_SEC))  NOMBRE_SECCION   FROM COT_ENC_SECCIONES S  JOIN  (COT_SECCIONES C  LEFT  OUTER  JOIN  COT_SECCIONES_SINONIMOS CS ON CS.COD_SECCION = C.COD_SECCION AND CS.C_EMP = C.C_EMP AND CS.IDIOMA = #idioma) ON S.COD_SECCION = C.COD_SECCION AND S.C_EMP = C.C_EMP  WHERE C.TIPO_SECCION =  'PRE' ",null);
	protected Query queryQUERY2 = new Query("QUERY2","DETAIL","WHERE C.TIPO_SECCION =  'ENC'",null,"ORDER BY C.ORDEN ASC"," SELECT  S.C_EMP   ,S.PER   ,S.C_AGR   ,S.COT   ,S.REV   ,S.COD_SECCION   ,S.DESCRIPCION   , NVL (S.ETIQUETA, NVL (CS.DESCRIPCION,C.NOMBRE_SEC))  NOMBRE_SECCION   FROM COT_ENC_SECCIONES S  JOIN  (COT_SECCIONES C  LEFT  OUTER  JOIN  COT_SECCIONES_SINONIMOS CS ON CS.COD_SECCION = C.COD_SECCION AND CS.C_EMP = C.C_EMP AND CS.IDIOMA = #idioma) ON S.COD_SECCION = C.COD_SECCION AND S.C_EMP = C.C_EMP  WHERE C.TIPO_SECCION =  'ENC' ",null);
	protected Query queryQUERY3 = new Query("QUERY3","DETAIL","WHERE C.TIPO_SECCION =  'PIE'",null,"ORDER BY C.ORDEN ASC"," SELECT  S.C_EMP   ,S.PER   ,S.C_AGR   ,S.COT   ,S.REV   ,S.COD_SECCION   ,S.DESCRIPCION   , NVL (S.ETIQUETA, NVL (CS.DESCRIPCION,C.NOMBRE_SEC))  NOMBRE_SECCION   FROM COT_ENC_SECCIONES S  JOIN  (COT_SECCIONES C  LEFT  OUTER  JOIN  COT_SECCIONES_SINONIMOS CS ON CS.COD_SECCION = C.COD_SECCION AND CS.C_EMP = C.C_EMP AND CS.IDIOMA = #idioma) ON S.COD_SECCION = C.COD_SECCION AND S.C_EMP = C.C_EMP  WHERE C.TIPO_SECCION =  'PIE' ",null);
	protected Query queryQUERY4 = new Query("QUERY4","DETAIL",null,null,"ORDER BY C.COD"," SELECT  C.C_EMP   ,C.COT   ,C.REV   ,C.C_AGR   ,C.CAN   ,C.UNIDAD   ,C.PER   ,C.COD   ,C.INF7   , NVL (A.NOM_LARGO,A.NOM)  NOM_ARTICULO  ,C.NOM    FROM COT_DET C  JOIN  ARTICULO A ON A.COD = C.COD AND A.C_EMP = C.C_EMP",null);
	protected Query queryQUERY5 = new Query("QUERY5","DETAIL",null,null,null," SELECT  C.C_EMP   ,C.NUM_DOC  COT  ,C.REV   ,C.C_AGR   ,C.PER   ,C.COD_COSTO   ,C.VALOR   , NVL (S.DESCRIPCION,F.NOMBRE)  NOMBRE_CARGO   FROM FAC_COSTOS_COT C  JOIN  FAC_COSTOS_ADIC F ON C.COD_COSTO = F.CODIGO AND C.C_EMP = F.C_EMP  LEFT  OUTER  JOIN  FAC_SINONIMO_COSTOS S ON S.CODIGO = C.COD_COSTO AND S.C_EMP = C.C_EMP AND S.IDIOMA = #idioma",null);
	protected Group groupGROUP_ENCABEZADO = new Group("GROUP_ENCABEZADO",queryQUERY0,"NONE",null,0);
	protected Group groupGROUP_DETALLE = new Group("GROUP_DETALLE",queryQUERY0,"NONE",null,0);
	protected Group groupCOSTOS_ADIC = new Group("COSTOS_ADIC",queryQUERY5,"NONE",null,0);
	protected Group groupDESCRIPCIONES_DETALLE = new Group("DESCRIPCIONES_DETALLE",queryQUERY4,"NONE",null,0);
	protected Group groupSECCIONES_PIE = new Group("SECCIONES_PIE",queryQUERY3,"NONE",null,0);
	protected Group groupSECCIONES_ENC = new Group("SECCIONES_ENC",queryQUERY2,"NONE",null,0);
	protected Group groupSECCIONES_PRE = new Group("SECCIONES_PRE",queryQUERY1,"NONE",null,0);
	protected GroupField groupFieldGROUP_ENCABEZADOC_EMP1 = new GroupField("C_EMP1",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPER1 = new GroupField("PER1",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOC_AGR1 = new GroupField("C_AGR1",2,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOCOT1 = new GroupField("COT1",3,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOREV1 = new GroupField("REV1",4,"java.math.BigInteger",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADON_IDE = new GroupField("N_IDE",5,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOCOD_SUC = new GroupField("COD_SUC",6,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOEMI = new GroupField("EMI",7,"java.sql.Date",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOVEN = new GroupField("VEN",8,"java.sql.Date",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOBRU = new GroupField("BRU",9,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODES = new GroupField("DES",10,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOMER = new GroupField("MER",11,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOIVA = new GroupField("IVA",12,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOTOT = new GroupField("TOT",13,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOCOSTOS_ADIC = new GroupField("COSTOS_ADIC",14,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOTOTD = new GroupField("TOTD",15,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOMON = new GroupField("MON",16,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOTASA = new GroupField("TASA",17,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOC_VEN = new GroupField("C_VEN",18,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOCOD_INCOTERM = new GroupField("COD_INCOTERM",19,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOORIGEN = new GroupField("ORIGEN",21,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODESTINO = new GroupField("DESTINO",22,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOCOD_EMB = new GroupField("COD_EMB",23,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_DETALLECOD = new GroupField("COD",25,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLEUNIDAD = new GroupField("UNIDAD",26,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLECAN = new GroupField("CAN",27,"java.math.BigDecimal",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLEVEN1 = new GroupField("VEN1",28,"java.math.BigDecimal",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLEIVA1 = new GroupField("IVA1",29,"java.lang.Double",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLESubtotal = new GroupField("Subtotal",0,"java.lang.String","0",null,"NONE",null,null,"REPORT","REPORT","subtotal_method","FORMULA",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLEColor_reg = new GroupField("color_reg",0,"java.lang.Double","0",null,"ASC","COUNT",groupGROUP_DETALLE,"GROUP_ENCABEZADO","REPORT",null,"SUMMARY",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLENOMBRE_ARTICULO = new GroupField("NOMBRE_ARTICULO",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","nombre_articulo_method","FORMULA",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_DETALLENOM = new GroupField("NOM",36,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_DETALLE,this);
	protected GroupField groupFieldGROUP_ENCABEZADOZONA = new GroupField("ZONA",24,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODATOS_CLIENTE = new GroupField("DATOS_CLIENTE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","datos_cliente_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADONOMBRE_CLIENTE = new GroupField("NOMBRE_CLIENTE",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODIR_CLIENTE = new GroupField("DIR_CLIENTE",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOTEL_CLIENTE = new GroupField("TEL_CLIENTE",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOUBICACION_CLIENTE = new GroupField("UBICACION_CLIENTE",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOEMAIL_CLIENTE = new GroupField("EMAIL_CLIENTE",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODIAS_VALIDEZ = new GroupField("DIAS_VALIDEZ",0,"java.lang.String","0",null,"NONE",null,null,"REPORT","REPORT","dias_validez_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADONOMBRE_EMBALAJE = new GroupField("NOMBRE_EMBALAJE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","nombre_embalaje_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOMONEDA_TEXTO = new GroupField("MONEDA_TEXTO",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","moneda_texto_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODESTINO_NOMBRE = new GroupField("DESTINO_NOMBRE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","destino_nombre_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldCOSTOS_ADICC_EMP6 = new GroupField("C_EMP6",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICCOT6 = new GroupField("COT6",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICREV6 = new GroupField("REV6",2,"java.math.BigInteger",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICC_AGR6 = new GroupField("C_AGR6",3,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICPER6 = new GroupField("PER6",4,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICCOD_COSTO = new GroupField("COD_COSTO",5,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICVALOR = new GroupField("VALOR",6,"java.math.BigDecimal",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICNOMBRE_CARGO = new GroupField("NOMBRE_CARGO",7,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldCOSTOS_ADICCOUNT_COSTOS = new GroupField("COUNT_COSTOS",0,"java.lang.Double","0",null,"ASC","COUNT",groupCOSTOS_ADIC,"REPORT","REPORT",null,"SUMMARY",null,false,0,groupCOSTOS_ADIC,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLECOD1 = new GroupField("COD1",7,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEC_EMP5 = new GroupField("C_EMP5",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLECOT5 = new GroupField("COT5",1,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEREV5 = new GroupField("REV5",2,"java.math.BigInteger",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEC_AGR5 = new GroupField("C_AGR5",3,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEPER5 = new GroupField("PER5",6,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEINF7 = new GroupField("INF7",8,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLENOM_ARTICULO = new GroupField("NOM_ARTICULO",9,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEDESCRIP_ARTICULO = new GroupField("DESCRIP_ARTICULO",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","descrip_articulo_method","FORMULA",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLECAN1 = new GroupField("CAN1",4,"java.math.BigDecimal",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLEUNIDAD1 = new GroupField("UNIDAD1",5,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLECOUNT_DET = new GroupField("COUNT_DET",0,"java.lang.Double","0",null,"ASC","COUNT",groupDESCRIPCIONES_DETALLE,"REPORT","REPORT",null,"SUMMARY",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldDESCRIPCIONES_DETALLENOM1 = new GroupField("NOM1",10,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupDESCRIPCIONES_DETALLE,this);
	protected GroupField groupFieldSECCIONES_PIEC_EMP4 = new GroupField("C_EMP4",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIEPER4 = new GroupField("PER4",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIEC_AGR4 = new GroupField("C_AGR4",2,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIECOT4 = new GroupField("COT4",3,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIEREV4 = new GroupField("REV4",4,"java.math.BigInteger",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIECOD_SECCION2 = new GroupField("COD_SECCION2",5,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIEDESCRIPCION2 = new GroupField("DESCRIPCION2",6,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_PIENOMBRE_SECCION2 = new GroupField("NOMBRE_SECCION2",7,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PIE,this);
	protected GroupField groupFieldSECCIONES_ENCC_EMP3 = new GroupField("C_EMP3",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCPER3 = new GroupField("PER3",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCC_AGR3 = new GroupField("C_AGR3",2,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCCOT3 = new GroupField("COT3",3,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCREV3 = new GroupField("REV3",4,"java.math.BigInteger",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCCOD_SECCION1 = new GroupField("COD_SECCION1",5,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCDESCRIPCION1 = new GroupField("DESCRIPCION1",6,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_ENCNOMBRE_SECCION1 = new GroupField("NOMBRE_SECCION1",7,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_ENC,this);
	protected GroupField groupFieldSECCIONES_PREC_EMP2 = new GroupField("C_EMP2",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PREPER2 = new GroupField("PER2",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PREC_AGR2 = new GroupField("C_AGR2",2,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PRECOT2 = new GroupField("COT2",3,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PREREV2 = new GroupField("REV2",4,"java.math.BigInteger",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PRECOD_SECCION = new GroupField("COD_SECCION",5,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PREDESCRIPCION = new GroupField("DESCRIPCION",6,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldSECCIONES_PRENOMBRE_SECCION = new GroupField("NOMBRE_SECCION",7,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupSECCIONES_PRE,this);
	protected GroupField groupFieldGROUP_ENCABEZADOIDIOMA = new GroupField("IDIOMA",20,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADODESPACHO = new GroupField("DESPACHO",30,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOTERMINO_PAGO = new GroupField("TERMINO_PAGO",31,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_TOTAL_BRUTO = new GroupField("PROMPT_TOTAL_BRUTO",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","prompt_total_bruto_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_TOTAL_DESCUENTO = new GroupField("PROMPT_TOTAL_DESCUENTO",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","prompt_total_descuento_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_TOTAL_BASE = new GroupField("PROMPT_TOTAL_BASE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","prompt_total_base_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_TOTAL_IVA = new GroupField("PROMPT_TOTAL_IVA",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","prompt_total_iva_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_TOTAL_PARCIAL = new GroupField("PROMPT_TOTAL_PARCIAL",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","prompt_total_parcial_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_TOTAL_NETO = new GroupField("PROMPT_TOTAL_NETO",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","prompt_total_neto_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOTIEMPO_ENTREGA = new GroupField("TIEMPO_ENTREGA",32,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOLUGAR_DESTINO = new GroupField("LUGAR_DESTINO",33,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPROMPT_DESTINO_NOMBRE = new GroupField("PROMPT_DESTINO_NOMBRE",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOPER_CARGO = new GroupField("PER_CARGO",34,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOCARGO = new GroupField("CARGO",35,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOFIRMA_VENDEDOR = new GroupField("FIRMA_VENDEDOR",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","firma_vendedor_method","FORMULA",null,false,0,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADONOMBRE_VENDEDOR = new GroupField("NOMBRE_VENDEDOR",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldGROUP_ENCABEZADOEMAIL_VENDEDOR = new GroupField("EMAIL_VENDEDOR",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,groupGROUP_ENCABEZADO,this);
	protected GroupField groupFieldFormula_columnsPARAMETROS = new GroupField("PARAMETROS",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","parametros_method","FORMULA",null,false,0,tempGroup,this);
	protected GroupField groupFieldPlaceholder_columnsLOGO_EMP = new GroupField("LOGO_EMP",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Image",true,10,tempGroup,this);
	protected GraphicsObjectServer graphicServergraphicG_title = new GraphicsObjectServer("G_title",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,164,100,50,false,false,-1,0,null,0,0,new Font("Courier New",1,14),false,"Parámetros del reporte");
	protected GraphicsObjectServer graphicServergraphicG_hint = new GraphicsObjectServer("G_hint",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,276,100,80,false,false,-1,0,null,0,0,new Font("Courier New",1,14),false,"Escriba los valores para el parámetro.");
	protected GraphicsObjectServer graphicServergraphicG_cot = new GraphicsObjectServer("G_cot",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,31,100,110,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"cot");
	protected GraphicsObjectServer graphicServergraphicG_rev = new GraphicsObjectServer("G_rev",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,31,100,140,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"rev");
	protected GraphicsObjectServer graphicServergraphicG_c_agr = new GraphicsObjectServer("G_c_agr",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,45,100,170,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"c_agr");
	protected GraphicsObjectServer graphicServergraphicG_per = new GraphicsObjectServer("G_per",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,31,100,200,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"per");
	protected GraphicsObjectServer graphicServergraphicG_c_emp = new GraphicsObjectServer("G_c_emp",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,45,100,230,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"c_emp");
	protected GraphicsObjectServer graphicServergraphicTEXT_GRAPHIC0 = new GraphicsObjectServer("TEXT_GRAPHIC0",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",14,27,79,264,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"Ocultar totales");
	protected DataLink dataLinkLINK0 = new DataLink(groupFieldGROUP_ENCABEZADOC_EMP1,groupFieldSECCIONES_PREC_EMP2,groupGROUP_ENCABEZADO,groupSECCIONES_PRE,"E.C_EMP","S.C_EMP","=");
	protected DataLink dataLinkLINK1 = new DataLink(groupFieldGROUP_ENCABEZADOPER1,groupFieldSECCIONES_PREPER2,groupGROUP_ENCABEZADO,groupSECCIONES_PRE,"E.PER","S.PER","=");
	protected DataLink dataLinkLINK2 = new DataLink(groupFieldGROUP_ENCABEZADOC_AGR1,groupFieldSECCIONES_PREC_AGR2,groupGROUP_ENCABEZADO,groupSECCIONES_PRE,"E.C_AGR","S.C_AGR","=");
	protected DataLink dataLinkLINK3 = new DataLink(groupFieldGROUP_ENCABEZADOCOT1,groupFieldSECCIONES_PRECOT2,groupGROUP_ENCABEZADO,groupSECCIONES_PRE,"E.COT","S.COT","=");
	protected DataLink dataLinkLINK4 = new DataLink(groupFieldGROUP_ENCABEZADOREV1,groupFieldSECCIONES_PREREV2,groupGROUP_ENCABEZADO,groupSECCIONES_PRE,"E.REV","S.REV","=");
	protected DataLink dataLinkLINK5 = new DataLink(groupFieldGROUP_ENCABEZADOC_EMP1,groupFieldSECCIONES_ENCC_EMP3,groupGROUP_ENCABEZADO,groupSECCIONES_ENC,"E.C_EMP","S.C_EMP","=");
	protected DataLink dataLinkLINK6 = new DataLink(groupFieldGROUP_ENCABEZADOPER1,groupFieldSECCIONES_ENCPER3,groupGROUP_ENCABEZADO,groupSECCIONES_ENC,"E.PER","S.PER","=");
	protected DataLink dataLinkLINK7 = new DataLink(groupFieldGROUP_ENCABEZADOC_AGR1,groupFieldSECCIONES_ENCC_AGR3,groupGROUP_ENCABEZADO,groupSECCIONES_ENC,"E.C_AGR","S.C_AGR","=");
	protected DataLink dataLinkLINK8 = new DataLink(groupFieldGROUP_ENCABEZADOCOT1,groupFieldSECCIONES_ENCCOT3,groupGROUP_ENCABEZADO,groupSECCIONES_ENC,"E.COT","S.COT","=");
	protected DataLink dataLinkLINK9 = new DataLink(groupFieldGROUP_ENCABEZADOREV1,groupFieldSECCIONES_ENCREV3,groupGROUP_ENCABEZADO,groupSECCIONES_ENC,"E.REV","S.REV","=");
	protected DataLink dataLinkLINK10 = new DataLink(groupFieldGROUP_ENCABEZADOC_EMP1,groupFieldSECCIONES_PIEC_EMP4,groupGROUP_ENCABEZADO,groupSECCIONES_PIE,"E.C_EMP","S.C_EMP","=");
	protected DataLink dataLinkLINK11 = new DataLink(groupFieldGROUP_ENCABEZADOPER1,groupFieldSECCIONES_PIEPER4,groupGROUP_ENCABEZADO,groupSECCIONES_PIE,"E.PER","S.PER","=");
	protected DataLink dataLinkLINK12 = new DataLink(groupFieldGROUP_ENCABEZADOC_AGR1,groupFieldSECCIONES_PIEC_AGR4,groupGROUP_ENCABEZADO,groupSECCIONES_PIE,"E.C_AGR","S.C_AGR","=");
	protected DataLink dataLinkLINK13 = new DataLink(groupFieldGROUP_ENCABEZADOCOT1,groupFieldSECCIONES_PIECOT4,groupGROUP_ENCABEZADO,groupSECCIONES_PIE,"E.COT","S.COT","=");
	protected DataLink dataLinkLINK14 = new DataLink(groupFieldGROUP_ENCABEZADOC_EMP1,groupFieldDESCRIPCIONES_DETALLEC_EMP5,groupGROUP_ENCABEZADO,groupDESCRIPCIONES_DETALLE,"E.C_EMP","C.C_EMP","=");
	protected DataLink dataLinkLINK15 = new DataLink(groupFieldGROUP_ENCABEZADOPER1,groupFieldDESCRIPCIONES_DETALLEPER5,groupGROUP_ENCABEZADO,groupDESCRIPCIONES_DETALLE,"E.PER","C.PER","=");
	protected DataLink dataLinkLINK16 = new DataLink(groupFieldGROUP_ENCABEZADOC_AGR1,groupFieldDESCRIPCIONES_DETALLEC_AGR5,groupGROUP_ENCABEZADO,groupDESCRIPCIONES_DETALLE,"E.C_AGR","C.C_AGR","=");
	protected DataLink dataLinkLINK17 = new DataLink(groupFieldGROUP_ENCABEZADOCOT1,groupFieldDESCRIPCIONES_DETALLECOT5,groupGROUP_ENCABEZADO,groupDESCRIPCIONES_DETALLE,"E.COT","C.COT","=");
	protected DataLink dataLinkLINK18 = new DataLink(groupFieldGROUP_ENCABEZADOREV1,groupFieldDESCRIPCIONES_DETALLEREV5,groupGROUP_ENCABEZADO,groupDESCRIPCIONES_DETALLE,"E.REV","C.REV","=");
	protected DataLink dataLinkLINK19 = new DataLink(groupFieldGROUP_ENCABEZADOC_EMP1,groupFieldCOSTOS_ADICC_EMP6,groupGROUP_ENCABEZADO,groupCOSTOS_ADIC,"E.C_EMP","C.C_EMP","=");
	protected DataLink dataLinkLINK20 = new DataLink(groupFieldGROUP_ENCABEZADOPER1,groupFieldCOSTOS_ADICPER6,groupGROUP_ENCABEZADO,groupCOSTOS_ADIC,"E.PER","C.PER","=");
	protected DataLink dataLinkLINK21 = new DataLink(groupFieldGROUP_ENCABEZADOC_AGR1,groupFieldCOSTOS_ADICC_AGR6,groupGROUP_ENCABEZADO,groupCOSTOS_ADIC,"E.C_AGR","C.C_AGR","=");
	protected DataLink dataLinkLINK22 = new DataLink(groupFieldGROUP_ENCABEZADOCOT1,groupFieldCOSTOS_ADICCOT6,groupGROUP_ENCABEZADO,groupCOSTOS_ADIC,"E.COT","COT","=");
	protected DataLink dataLinkLINK23 = new DataLink(groupFieldGROUP_ENCABEZADOREV1,groupFieldCOSTOS_ADICREV6,groupGROUP_ENCABEZADO,groupCOSTOS_ADIC,"E.REV","C.REV","=");
	protected ReportRegion reportRegionHeaderBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionHeaderMargin = new ReportRegion("MARGIN");
	protected ReportRegion reportRegionMainBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionMainMargin = new ReportRegion("MARGIN");
	protected ReportRegion reportRegionTrailerBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionTrailerMargin = new ReportRegion("MARGIN");
	protected ReportMargin reportMarginHeader = new ReportMargin(70,34,34,70);
	protected ReportSection reportSectionHeader = new ReportSection("HEADER",reportMarginHeader,792,612,reportRegionHeaderBody,reportRegionHeaderMargin,"Portrait");
	protected ReportMargin reportMarginMain = new ReportMargin(70,34,28,46);
	protected ReportSection reportSectionMain = new ReportSection("MAIN",reportMarginMain,792,612,reportRegionMainBody,reportRegionMainMargin,"Portrait");
	protected ReportMargin reportMarginTrailer = new ReportMargin(70,34,34,70);
	protected ReportSection reportSectionTrailer = new ReportSection("TRAILER",reportMarginTrailer,792,612,reportRegionTrailerBody,reportRegionTrailerMargin,"Portrait");

	public Cotizaciones_Print_class1() throws Exception {
		super();
	}
}