package com.aspsols.cotizaciones.reportes;

import java.awt.Font;
import  java.util.Map;
import java.util.Vector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.util.Iterator;
import java.util.Hashtable;
import com.aspsolutions.jdbc.ObjectType;
import com.aspsolutions.jframework.Exceptions.RecordIdNotFoundException;
import com.aspsolutions.jframework.standar.JReportUtils;
import com.aspsolutions.jreports.server.JReport;
import com.aspsolutions.jreports.server.PresentationRules;
import com.aspsolutions.jreports.server.QueryLogic;
import com.aspsolutions.jreports.server.presentation.FormatException;
import com.aspsolutions.jreports.server.presentation.ReportEllipse;
import com.aspsolutions.jreports.server.presentation.ReportFieldPresentation;
import com.aspsolutions.jreports.server.presentation.ReportLine;
import com.aspsolutions.jreports.server.presentation.ReportMargin;
import com.aspsolutions.jreports.server.presentation.ReportRectangle;
import com.aspsolutions.jreports.server.presentation.ReportImage;
import com.aspsolutions.jreports.server.presentation.ReportRegion;
import com.aspsolutions.jreports.server.presentation.ReportRepetitiveFrame;
import com.aspsolutions.jreports.server.presentation.ReportSection;
import com.aspsolutions.jreports.server.querylogic.DataLink;
import com.aspsolutions.jreports.server.querylogic.Group;
import com.aspsolutions.jreports.server.querylogic.GroupField;
import com.aspsolutions.jreports.server.querylogic.Query;
import com.aspsolutions.jreports.server.querylogic.querycomponents.FromTables;
import com.aspsolutions.jreports.server.runtime.GroupPointer;
import com.aspsolutions.jreports.server.runtime.JReportRuntime;
import com.aspsolutions.jreports.server.runtime.QueryRecords;
import com.aspsolutions.jreports.server.runtime.ReportField;
import com.aspsolutions.jreports.server.presentation.ReportText;
import com.aspsolutions.jreports.server.presentation.ReportFrame;
import com.aspsolutions.jreports.server.presentation.ReportRoundedRectangle;
import com.aspsolutions.jframework.standar.ASPString;
import com.aspsolutions.jreports.server.querylogic.querycomponents.SelectColumns;
import com.aspsolutions.jreports.server.parameters.ParameterForm;
import com.aspsolutions.jframework.Server.DataFieldDefinition;
import com.aspsolutions.jframework.Server.GraphicsObjectServer;
import javax.swing.FocusManager;
import com.aspsolutions.jframework.standar.ASPMath;
import com.aspsolutions.jframework.Server.RecordGroupServer;
import com.aspsolutions.jframework.Server.HelpListServer;
import com.aspsolutions.jreports.server.presentation.ReportChart;
import com.aspsolutions.jframework.Server.JApplicationServer;
import com.aspsolutions.jframework.standar.ASPConverter;
import com.aspsolutions.jframework.standar.ASPSQLFunctions;
import com.aspsolutions.jframework.Utils.SqlParameter;
import com.aspsolutions.jframework.Exceptions.NoDataFoundException;
import com.aspsolutions.jframework.Exceptions.TooManyRows;
import com.aspsolutions.jframework.Exceptions.NumericOrValueException;
import com.aspsolutions.jframework.srw.SRWProgramAbort;
import com.aspsolutions.jframework.standar.ASPLogicalOperators;
import java.awt.Font;
import com.aspsolutions.jreports.server.LayoutTextVariables;
import com.aspsolutions.jframework.Server.ProcedureCallParameters;
import com.aspsolutions.jframework.standar.Utils;
import com.aspsolutions.jreports.server.presentation.PresentationFormat;
import com.aspsolutions.jreports.server.presentation.Conditions;
import com.aspsolutions.jframework.Server.ColumnSpecifications;
import com.aspsolutions.jreports.server.presentation.ReportButton;
import com.aspsolutions.jreports.server.presentation.PageNumbering;
import com.aspsolutions.jframework.Exceptions.DupValOnIndexException;
import com.aspsolutions.jreports.server.presentation.ReportAnchor;
import com.aspsolutions.jframework.standar.ASPCollection;
import com.aspsolutions.jreports.server.presentation.ChartParameter;
import com.aspsolutions.jreports.server.presentation.ChartColumn;
import static com.aspsolutions.jframework.standar.ASPConverter.*;
import static com.aspsolutions.jframework.standar.ASPLogicalOperators.*;
import static com.aspsolutions.jframework.standar.ASPMath.*;
import static com.aspsolutions.jframework.standar.ASPString.*;
import com.aspsolutions.jframework.standar.ASPAccessFile;
import com.aspsolutions.jframework.srw.SRWRunReportFailure;

public class Cotizaciones_Print_class3 extends Cotizaciones_Print_class2 {
	protected ReportText reportTextMainBodyText_graphic5 = new ReportText("TEXT_GRAPHIC5",20,151,reportRegionMainBody,3,reportFrameMainBodyEncabezado_cot,"Fecha /",11,38,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic6 = new ReportText("TEXT_GRAPHIC6",58,151,reportRegionMainBody,4,reportFrameMainBodyEncabezado_cot,"Date:",11,29,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic7 = new ReportText("TEXT_GRAPHIC7",20,184,reportRegionMainBody,7,reportFrameMainBodyEncabezado_cot,"Origen /",11,41,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic8 = new ReportText("TEXT_GRAPHIC8",61,184,reportRegionMainBody,8,reportFrameMainBodyEncabezado_cot,"Origin: ",11,34,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic10 = new ReportText("TEXT_GRAPHIC10",118,162,reportRegionMainBody,10,reportFrameMainBodyEncabezado_cot,"Offer validity:",11,64,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic9 = new ReportText("TEXT_GRAPHIC9",20,162,reportRegionMainBody,9,reportFrameMainBodyEncabezado_cot,"Validez de la oferta /",11,98,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic11 = new ReportText("TEXT_GRAPHIC11",20,173,reportRegionMainBody,13,reportFrameMainBodyEncabezado_cot,"Embalaje /",11,51,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic12 = new ReportText("TEXT_GRAPHIC12",71,173,reportRegionMainBody,14,reportFrameMainBodyEncabezado_cot,"Packing:",11,41,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic14 = new ReportText("TEXT_GRAPHIC14",342,151,reportRegionMainBody,15,reportFrameMainBodyEncabezado_cot,"Currency:",11,46,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic13 = new ReportText("TEXT_GRAPHIC13",295,151,reportRegionMainBody,17,reportFrameMainBodyEncabezado_cot,"Moneda /",11,47,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic16 = new ReportText("TEXT_GRAPHIC16",295,162,reportRegionMainBody,18,reportFrameMainBodyEncabezado_cot,"Destino /",11,45,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic17 = new ReportText("TEXT_GRAPHIC17",340,162,reportRegionMainBody,21,reportFrameMainBodyEncabezado_cot,"Final destination:",11,80,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic25 = new ReportText("TEXT_GRAPHIC25",20,195,reportRegionMainBody,59,reportFrameMainBodyEncabezado_cot,"Despacho /",11,55,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic26 = new ReportText("TEXT_GRAPHIC26",75,195,reportRegionMainBody,60,reportFrameMainBodyEncabezado_cot,"Delivery:",11,43,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic30 = new ReportText("TEXT_GRAPHIC30",295,173,reportRegionMainBody,79,reportFrameMainBodyEncabezado_cot,"Tiempo de entrega /",11,98,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic31 = new ReportText("TEXT_GRAPHIC31",393,173,reportRegionMainBody,80,reportFrameMainBodyEncabezado_cot,"Delivery Time:",11,69,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic36 = new ReportText("TEXT_GRAPHIC36",337,184,reportRegionMainBody,84,reportFrameMainBodyEncabezado_cot,"Include:",11,38,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED","TEXT_GRAPHIC36_formatEvent",0,-1);
	protected ReportText reportTextMainBodyText_graphic32 = new ReportText("TEXT_GRAPHIC32",295,184,reportRegionMainBody,85,reportFrameMainBodyEncabezado_cot,"Incluye /",11,42,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED","TEXT_GRAPHIC32_formatEvent",0,-1);
	protected ReportText reportTextMainBodyText_graphic28 = new ReportText("TEXT_GRAPHIC28",115,206,reportRegionMainBody,132,reportFrameMainBodyTermino_pago_frame,"Payment terms:",11,76,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic27 = new ReportText("TEXT_GRAPHIC27",20,206,reportRegionMainBody,133,reportFrameMainBodyTermino_pago_frame,"Términos de pago /",11,95,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic24 = new ReportText("TEXT_GRAPHIC24",422,379,reportRegionMainBody,26,reportFrameMainBodyDetalle_frame,"Total Price",9,98,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic22 = new ReportText("TEXT_GRAPHIC22",353,379,reportRegionMainBody,27,reportFrameMainBodyDetalle_frame,"Unit. Price",9,69,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic21 = new ReportText("TEXT_GRAPHIC21",303,379,reportRegionMainBody,28,reportFrameMainBodyDetalle_frame,"Quantity",9,50,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic20 = new ReportText("TEXT_GRAPHIC20",253,379,reportRegionMainBody,29,reportFrameMainBodyDetalle_frame,"Unit",9,50,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic19 = new ReportText("TEXT_GRAPHIC19",83,379,reportRegionMainBody,30,reportFrameMainBodyDetalle_frame,"Item Name",9,170,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic18 = new ReportText("TEXT_GRAPHIC18",20,379,reportRegionMainBody,31,reportFrameMainBodyDetalle_frame,"Code",9,63,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic15 = new ReportText("TEXT_GRAPHIC15",83,370,reportRegionMainBody,32,reportFrameMainBodyDetalle_frame,"Nombre Artículo",9,170,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyTsubtotal = new ReportText("tSubtotal",422,370,reportRegionMainBody,33,reportFrameMainBodyDetalle_frame,"Subtotal",9,98,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyTcod = new ReportText("tCod",20,370,reportRegionMainBody,34,reportFrameMainBodyDetalle_frame,"Código",9,63,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyTcantidad = new ReportText("tCantidad",303,370,reportRegionMainBody,35,reportFrameMainBodyDetalle_frame,"Cantidad",9,50,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyTunidad = new ReportText("tUnidad",253,370,reportRegionMainBody,36,reportFrameMainBodyDetalle_frame,"Unidad",9,50,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyT_ven1 = new ReportText("t_VEN1",353,370,reportRegionMainBody,37,reportFrameMainBodyDetalle_frame,"Precio Venta",9,69,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic45 = new ReportText("TEXT_GRAPHIC45",148,289,reportRegionMainBody,119,reportFrameMainBodyDesc_det_frame,"Nombre Articulo",11,372,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic44 = new ReportText("TEXT_GRAPHIC44",50,289,reportRegionMainBody,118,reportFrameMainBodyDesc_det_frame,"Unidad",11,44,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic48 = new ReportText("TEXT_GRAPHIC48",148,300,reportRegionMainBody,120,reportFrameMainBodyDesc_det_frame,"Item Name",11,372,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic43 = new ReportText("TEXT_GRAPHIC43",94,289,reportRegionMainBody,117,reportFrameMainBodyDesc_det_frame,"Cantidad",11,54,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic46 = new ReportText("TEXT_GRAPHIC46",94,300,reportRegionMainBody,121,reportFrameMainBodyDesc_det_frame,"Quantity",11,54,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic47 = new ReportText("TEXT_GRAPHIC47",50,300,reportRegionMainBody,122,reportFrameMainBodyDesc_det_frame,"Unit",11,44,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic49 = new ReportText("TEXT_GRAPHIC49",20,289,reportRegionMainBody,123,reportFrameMainBodyDesc_det_frame,"Item",11,30,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic50 = new ReportText("TEXT_GRAPHIC50",20,300,reportRegionMainBody,124,reportFrameMainBodyDesc_det_frame,"Item",11,30,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,10),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic29 = new ReportText("TEXT_GRAPHIC29",22,587,reportRegionMainBody,78,reportFrameMainBodyFirma,"Comercial",10,255,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,8),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic37 = new ReportText("TEXT_GRAPHIC37",20,401,reportRegionMainBody,87,reportFrameMainBodyFrame_detalle_sin_tot,"Código",9,63,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic38 = new ReportText("TEXT_GRAPHIC38",83,401,reportRegionMainBody,88,reportFrameMainBodyFrame_detalle_sin_tot,"Nombre Artículo",9,335,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic39 = new ReportText("TEXT_GRAPHIC39",418,401,reportRegionMainBody,89,reportFrameMainBodyFrame_detalle_sin_tot,"Unidad",9,50,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic40 = new ReportText("TEXT_GRAPHIC40",468,401,reportRegionMainBody,90,reportFrameMainBodyFrame_detalle_sin_tot,"Cantidad",9,52,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",1,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic23 = new ReportText("TEXT_GRAPHIC23",20,410,reportRegionMainBody,126,reportFrameMainBodyFrame_detalle_sin_tot,"Code",9,63,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic51 = new ReportText("TEXT_GRAPHIC51",83,410,reportRegionMainBody,127,reportFrameMainBodyFrame_detalle_sin_tot,"Item Name",9,335,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic52 = new ReportText("TEXT_GRAPHIC52",418,410,reportRegionMainBody,128,reportFrameMainBodyFrame_detalle_sin_tot,"Unit",9,50,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic53 = new ReportText("TEXT_GRAPHIC53",468,410,reportRegionMainBody,129,reportFrameMainBodyFrame_detalle_sin_tot,"Quantity",9,52,new Color(0,0,0),new Color(204,204,204),null,new Font("Arial",2,8),"ALLPAGES",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic3 = new ReportText("TEXT_GRAPHIC3",414,4,reportRegionMainBody,99,reportFrameMainBodyPresentacion,"Quote",14,39,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic2 = new ReportText("TEXT_GRAPHIC2",355,4,reportRegionMainBody,100,reportFrameMainBodyPresentacion,"Cotización /",14,59,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic4 = new ReportText("TEXT_GRAPHIC4",315,18,reportRegionMainBody,101,reportFrameMainBodyPresentacion,"No. &Cot Rev. &Rev",14,174,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic0 = new ReportText("TEXT_GRAPHIC0",20,36,reportRegionMainBody,104,reportFrameMainBodyDatos_cliente,"Señor(es) /",11,55,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic1 = new ReportText("TEXT_GRAPHIC1",75,36,reportRegionMainBody,109,reportFrameMainBodyDatos_cliente,"Mr(s)",11,40,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic41 = new ReportText("TEXT_GRAPHIC41",222,356,reportRegionMainBody,115,reportFrameMainBodyPresupuesto_frame,"Presupuesto /",11,69,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic42 = new ReportText("TEXT_GRAPHIC42",290,356,reportRegionMainBody,116,reportFrameMainBodyPresupuesto_frame,"Budget",11,40,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",2,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic33 = new ReportText("TEXT_GRAPHIC33",420,59,reportRegionMainMargin,1,null,"Página &<PageNumber> de &<TotalPages>",10,158,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,8),"DEFAULT",false,false,false,false,4,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic34 = new ReportText("TEXT_GRAPHIC34",34,749,reportRegionMainMargin,3,reportFrameMainMarginReserva_derechos,"Solagro S.A.S., se reserva el derecho de corregir esta oferta por errores u omisiones",10,544,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,8),"DEFAULT",false,false,false,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic35 = new ReportText("TEXT_GRAPHIC35",34,758,reportRegionMainMargin,4,reportFrameMainMarginReserva_derechos,"Solagro S.A.S., reserves the right to amend this offer to correct errors and omissions",10,544,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,8),"DEFAULT",false,false,false,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportLine reportLineMainBodyLine1 = new ReportLine("LINE1",20,278,reportRegionMainBody,97,repetitiveFrameMainBodySecciones_enc,520,279,new Color(0,0,0),null,1,"DEFAULT",false,false,false,null);
	protected ReportLine reportLineMainBodyLine0 = new ReportLine("LINE0",20,345,reportRegionMainBody,96,repetitiveFrameMainBodyDesc_det,520,346,new Color(0,0,0),null,1,"DEFAULT",false,false,false,null);

	public Cotizaciones_Print_class3() throws Exception {
		super();
	}
}