package com.aspsols.cotizaciones.reportes;

import java.awt.Font;
import  java.util.Map;
import java.util.Vector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.util.Iterator;
import java.util.Hashtable;
import com.aspsolutions.jdbc.ObjectType;
import com.aspsolutions.jframework.Exceptions.RecordIdNotFoundException;
import com.aspsolutions.jframework.standar.JReportUtils;
import com.aspsolutions.jreports.server.JReport;
import com.aspsolutions.jreports.server.PresentationRules;
import com.aspsolutions.jreports.server.QueryLogic;
import com.aspsolutions.jreports.server.presentation.FormatException;
import com.aspsolutions.jreports.server.presentation.ReportEllipse;
import com.aspsolutions.jreports.server.presentation.ReportFieldPresentation;
import com.aspsolutions.jreports.server.presentation.ReportLine;
import com.aspsolutions.jreports.server.presentation.ReportMargin;
import com.aspsolutions.jreports.server.presentation.ReportRectangle;
import com.aspsolutions.jreports.server.presentation.ReportImage;
import com.aspsolutions.jreports.server.presentation.ReportRegion;
import com.aspsolutions.jreports.server.presentation.ReportRepetitiveFrame;
import com.aspsolutions.jreports.server.presentation.ReportSection;
import com.aspsolutions.jreports.server.querylogic.DataLink;
import com.aspsolutions.jreports.server.querylogic.Group;
import com.aspsolutions.jreports.server.querylogic.GroupField;
import com.aspsolutions.jreports.server.querylogic.Query;
import com.aspsolutions.jreports.server.querylogic.querycomponents.FromTables;
import com.aspsolutions.jreports.server.runtime.GroupPointer;
import com.aspsolutions.jreports.server.runtime.JReportRuntime;
import com.aspsolutions.jreports.server.runtime.QueryRecords;
import com.aspsolutions.jreports.server.runtime.ReportField;
import com.aspsolutions.jreports.server.presentation.ReportText;
import com.aspsolutions.jreports.server.presentation.ReportFrame;
import com.aspsolutions.jreports.server.presentation.ReportRoundedRectangle;
import com.aspsolutions.jframework.standar.ASPString;
import com.aspsolutions.jreports.server.querylogic.querycomponents.SelectColumns;
import com.aspsolutions.jreports.server.parameters.ParameterForm;
import com.aspsolutions.jframework.Server.DataFieldDefinition;
import com.aspsolutions.jframework.Server.GraphicsObjectServer;
import javax.swing.FocusManager;
import com.aspsolutions.jframework.standar.ASPMath;
import com.aspsolutions.jframework.Server.RecordGroupServer;
import com.aspsolutions.jframework.Server.HelpListServer;
import com.aspsolutions.jreports.server.presentation.ReportChart;
import com.aspsolutions.jframework.Server.JApplicationServer;
import com.aspsolutions.jframework.standar.ASPConverter;
import com.aspsolutions.jframework.standar.ASPSQLFunctions;
import com.aspsolutions.jframework.Utils.SqlParameter;
import com.aspsolutions.jframework.Exceptions.NoDataFoundException;
import com.aspsolutions.jframework.Exceptions.TooManyRows;
import com.aspsolutions.jframework.Exceptions.NumericOrValueException;
import com.aspsolutions.jframework.srw.SRWProgramAbort;
import com.aspsolutions.jframework.standar.ASPLogicalOperators;
import java.awt.Font;
import com.aspsolutions.jreports.server.LayoutTextVariables;
import com.aspsolutions.jframework.Server.ProcedureCallParameters;
import com.aspsolutions.jframework.standar.Utils;
import com.aspsolutions.jreports.server.presentation.PresentationFormat;
import com.aspsolutions.jreports.server.presentation.Conditions;
import com.aspsolutions.jframework.Server.ColumnSpecifications;
import com.aspsolutions.jreports.server.presentation.ReportButton;
import com.aspsolutions.jreports.server.presentation.PageNumbering;
import com.aspsolutions.jframework.Exceptions.DupValOnIndexException;
import com.aspsolutions.jreports.server.presentation.ReportAnchor;
import com.aspsolutions.jframework.standar.ASPCollection;
import com.aspsolutions.jreports.server.presentation.ChartParameter;
import com.aspsolutions.jreports.server.presentation.ChartColumn;
import static com.aspsolutions.jframework.standar.ASPConverter.*;
import static com.aspsolutions.jframework.standar.ASPLogicalOperators.*;
import static com.aspsolutions.jframework.standar.ASPMath.*;
import static com.aspsolutions.jframework.standar.ASPString.*;
import com.aspsolutions.jframework.standar.ASPAccessFile;
import com.aspsolutions.jframework.srw.SRWRunReportFailure;

public class informeDeVentasPorEmpresa_class1 extends JReportRuntime {
	
	protected QueryLogic queryLogic = new QueryLogic();
	protected Group tempGroup = new Group("GrupoTemporal");
	
	protected Query queryQUERY0 = new Query("QUERY0","MASTER","WHERE A.PER = #periodo AND A.C_EMP = #empresa",null,null," SELECT  A.C_EMP  EMPRESA  ,A.MON  MONEDA  ,A.PER  ACTUAL  ,A.VENTAS_ACT  VENTAS_AC  ,A.PASADO  PASADO  ,A.VENTAS_PAS  VENTAS_PA   FROM VENTAS_XEMP_ACT_JOIN A  WHERE A.PER = #periodo AND A.C_EMP = #empresa",null);
	protected Group groupGROUP_MONEDA = new Group("GROUP_MONEDA",queryQUERY0,"NONE",null,0);
	protected Group groupGROUP0 = new Group("GROUP0",queryQUERY0,"NONE",null,0);
	protected GroupField groupFieldGROUP_MONEDAMONEDA = new GroupField("MONEDA",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_MONEDA,this);
	protected GroupField groupFieldGROUP0EMPRESA1 = new GroupField("EMPRESA1",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0ACTUAL = new GroupField("ACTUAL",2,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0VENTAS_AC = new GroupField("VENTAS_AC",3,"java.lang.Integer",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0PASADO = new GroupField("PASADO",4,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0VENTAS_PA = new GroupField("VENTAS_PA",5,"java.lang.Integer",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0PORCENTAJE = new GroupField("PORCENTAJE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","porcentaje_method","FORMULA",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldFormula_columnsPorcentaje_total = new GroupField("porcentaje_total",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","porcentaje_total_method","FORMULA",null,false,0,tempGroup,this);
	protected GroupField groupFieldFormula_columnsNOM_EMP = new GroupField("NOM_EMP",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","nom_emp_method","FORMULA",null,false,0,tempGroup,this);
	protected GraphicsObjectServer graphicServergraphicRECTANGLE0 = new GraphicsObjectServer("RECTANGLE0",new Color(204,204,255),new Color(0,0,0),"RECTANGLE",160,300,59,88,false,true,1,0,"Normal",0,0,null,false,null);
	protected GraphicsObjectServer graphicServergraphicRECTANGLE1 = new GraphicsObjectServer("RECTANGLE1",new Color(204,204,255),new Color(0,0,0),"RECTANGLE",44,298,59,34,false,true,1,0,"Normal",0,0,null,false,null);
	protected GraphicsObjectServer graphicServergraphicG_title = new GraphicsObjectServer("G_title",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,164,100,50,false,false,-1,0,null,0,0,new Font("Courier New",1,14),false,"Parámetros del reporte");
	protected GraphicsObjectServer graphicServergraphicG_periodo = new GraphicsObjectServer("G_periodo",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",14,49,115,115,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"Periodo");
	protected GraphicsObjectServer graphicServergraphicTEXT_GRAPHIC0 = new GraphicsObjectServer("TEXT_GRAPHIC0",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",14,49,115,145,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"Empresa");
	protected ReportRegion reportRegionHeaderBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionHeaderMargin = new ReportRegion("MARGIN");
	protected ReportRegion reportRegionMainBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionMainMargin = new ReportRegion("MARGIN");
	protected ReportRegion reportRegionTrailerBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionTrailerMargin = new ReportRegion("MARGIN");
	protected ReportMargin reportMarginHeader = new ReportMargin(70,34,34,70);
	protected ReportSection reportSectionHeader = new ReportSection("HEADER",reportMarginHeader,792,612,reportRegionHeaderBody,reportRegionHeaderMargin,"Portrait");
	protected ReportMargin reportMarginMain = new ReportMargin(68,19,61,74);
	protected ReportSection reportSectionMain = new ReportSection("MAIN",reportMarginMain,792,563,reportRegionMainBody,reportRegionMainMargin,"Portrait");
	protected ReportMargin reportMarginTrailer = new ReportMargin(70,34,34,70);
	protected ReportSection reportSectionTrailer = new ReportSection("TRAILER",reportMarginTrailer,792,612,reportRegionTrailerBody,reportRegionTrailerMargin,"Portrait");

	public informeDeVentasPorEmpresa_class1() throws Exception {
		super();
	}
}