package com.aspsols.cotizaciones.reportes;

import java.awt.Font;
import  java.util.Map;
import java.util.Vector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.util.Iterator;
import java.util.Hashtable;
import com.aspsolutions.jdbc.ObjectType;
import com.aspsolutions.jframework.Exceptions.RecordIdNotFoundException;
import com.aspsolutions.jframework.standar.JReportUtils;
import com.aspsolutions.jreports.server.JReport;
import com.aspsolutions.jreports.server.PresentationRules;
import com.aspsolutions.jreports.server.QueryLogic;
import com.aspsolutions.jreports.server.presentation.FormatException;
import com.aspsolutions.jreports.server.presentation.ReportEllipse;
import com.aspsolutions.jreports.server.presentation.ReportFieldPresentation;
import com.aspsolutions.jreports.server.presentation.ReportLine;
import com.aspsolutions.jreports.server.presentation.ReportMargin;
import com.aspsolutions.jreports.server.presentation.ReportRectangle;
import com.aspsolutions.jreports.server.presentation.ReportImage;
import com.aspsolutions.jreports.server.presentation.ReportRegion;
import com.aspsolutions.jreports.server.presentation.ReportRepetitiveFrame;
import com.aspsolutions.jreports.server.presentation.ReportSection;
import com.aspsolutions.jreports.server.querylogic.DataLink;
import com.aspsolutions.jreports.server.querylogic.Group;
import com.aspsolutions.jreports.server.querylogic.GroupField;
import com.aspsolutions.jreports.server.querylogic.Query;
import com.aspsolutions.jreports.server.querylogic.querycomponents.FromTables;
import com.aspsolutions.jreports.server.runtime.GroupPointer;
import com.aspsolutions.jreports.server.runtime.JReportRuntime;
import com.aspsolutions.jreports.server.runtime.QueryRecords;
import com.aspsolutions.jreports.server.runtime.ReportField;
import com.aspsolutions.jreports.server.presentation.ReportText;
import com.aspsolutions.jreports.server.presentation.ReportFrame;
import com.aspsolutions.jreports.server.presentation.ReportRoundedRectangle;
import com.aspsolutions.jframework.standar.ASPString;
import com.aspsolutions.jreports.server.querylogic.querycomponents.SelectColumns;
import com.aspsolutions.jreports.server.parameters.ParameterForm;
import com.aspsolutions.jframework.Server.DataFieldDefinition;
import com.aspsolutions.jframework.Server.GraphicsObjectServer;
import javax.swing.FocusManager;
import com.aspsolutions.jframework.standar.ASPMath;
import com.aspsolutions.jframework.Server.RecordGroupServer;
import com.aspsolutions.jframework.Server.HelpListServer;
import com.aspsolutions.jreports.server.presentation.ReportChart;
import com.aspsolutions.jframework.Server.JApplicationServer;
import com.aspsolutions.jframework.standar.ASPConverter;
import com.aspsolutions.jframework.standar.ASPSQLFunctions;
import com.aspsolutions.jframework.Utils.SqlParameter;
import com.aspsolutions.jframework.Exceptions.NoDataFoundException;
import com.aspsolutions.jframework.Exceptions.TooManyRows;
import com.aspsolutions.jframework.Exceptions.NumericOrValueException;
import com.aspsolutions.jframework.srw.SRWProgramAbort;
import com.aspsolutions.jframework.standar.ASPLogicalOperators;
import java.awt.Font;
import com.aspsolutions.jreports.server.LayoutTextVariables;
import com.aspsolutions.jframework.Server.ProcedureCallParameters;
import com.aspsolutions.jframework.standar.Utils;
import com.aspsolutions.jreports.server.presentation.PresentationFormat;
import com.aspsolutions.jreports.server.presentation.Conditions;
import com.aspsolutions.jframework.Server.ColumnSpecifications;
import com.aspsolutions.jreports.server.presentation.ReportButton;
import com.aspsolutions.jreports.server.presentation.PageNumbering;
import com.aspsolutions.jframework.Exceptions.DupValOnIndexException;
import com.aspsolutions.jreports.server.presentation.ReportAnchor;
import com.aspsolutions.jframework.standar.ASPCollection;
import com.aspsolutions.jreports.server.presentation.ChartParameter;
import com.aspsolutions.jreports.server.presentation.ChartColumn;
import static com.aspsolutions.jframework.standar.ASPConverter.*;
import static com.aspsolutions.jframework.standar.ASPLogicalOperators.*;
import static com.aspsolutions.jframework.standar.ASPMath.*;
import static com.aspsolutions.jframework.standar.ASPString.*;
import com.aspsolutions.jframework.standar.ASPAccessFile;
import com.aspsolutions.jframework.srw.SRWRunReportFailure;

public class informeDeVentasPorEmpresa_class3 extends informeDeVentasPorEmpresa_class2 {
	protected ReportText reportTextMainBodyText_graphic1 = new ReportText("TEXT_GRAPHIC1",23,0,reportRegionMainBody,5,reportFrameMainBodyFrame2,"Compañia",11,120,new Color(255,255,255),new Color(0,51,153),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic3 = new ReportText("TEXT_GRAPHIC3",413,0,reportRegionMainBody,4,reportFrameMainBodyFrame2,"%",11,37,new Color(255,255,255),new Color(255,102,51),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic6 = new ReportText("TEXT_GRAPHIC6",182,0,reportRegionMainBody,10,reportFrameMainBodyFrame2,"Periodo actual",11,54,new Color(255,255,255),new Color(0,51,153),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic0 = new ReportText("TEXT_GRAPHIC0",143,0,reportRegionMainBody,11,reportFrameMainBodyFrame2,"Moneda",11,39,new Color(255,255,255),new Color(0,51,153),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic8 = new ReportText("TEXT_GRAPHIC8",294,0,reportRegionMainBody,12,reportFrameMainBodyFrame2,"Periodo pasado",11,59,new Color(255,255,255),new Color(255,102,51),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic9 = new ReportText("TEXT_GRAPHIC9",353,0,reportRegionMainBody,13,reportFrameMainBodyFrame2,"Ventas pasadas",11,60,new Color(255,255,255),new Color(255,102,51),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic7 = new ReportText("TEXT_GRAPHIC7",236,0,reportRegionMainBody,14,reportFrameMainBodyFrame2,"Ventas actuales",11,58,new Color(255,255,255),new Color(0,51,153),"Default,1,(0,0,0)",new Font("Arial",0,8),"DEFAULT",false,false,true,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic5 = new ReportText("TEXT_GRAPHIC5",111,24,reportRegionMainBody,19,reportFrameMainBodyFrame1,"Grafico de ventas por empresa por periodo en &mon",13,217,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,8),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginTitle = new ReportText("TITLE",181,9,reportRegionMainMargin,0,null,"SOLAGRO SOLUCIONES AGROINDRUSTRIALES S.A.S.",14,310,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,11),"DEFAULT",false,false,false,false,4,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic2 = new ReportText("TEXT_GRAPHIC2",403,36,reportRegionMainMargin,2,null,"Fecha:",10,27,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,8),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic4 = new ReportText("TEXT_GRAPHIC4",181,23,reportRegionMainMargin,3,null,"Informe de ventas por empresa del periodo &periodo",14,310,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,9),"DEFAULT",false,false,false,false,4,"FIXED","FIXED",null,0,-1);
	protected ReportChart reportChartMainBodyLayout_chart0 = new ReportChart("LAYOUT_CHART0",29,35,161,421,reportRegionMainBody,20,reportFrameMainBodyFrame1,"FIXED","FIXED",new Color(255,255,255),null,"DEFAULT",false,false,false);
	protected ReportImage reportRectangleMainMarginImage0 = new ReportImage("IMAGE0",34,9,reportRegionMainMargin,4,null,1,new Color(0,0,0),new Color(135,155,211),51,125,"Normal","logo.png","DEFAULT",false,false,false,null,0);  

	public informeDeVentasPorEmpresa_class3() throws Exception {
		super();
	}
}