package com.aspsols.cotizaciones.reportes;

import java.awt.Font;
import  java.util.Map;
import java.util.Vector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.util.Iterator;
import java.util.Hashtable;
import com.aspsolutions.jdbc.ObjectType;
import com.aspsolutions.jframework.Exceptions.RecordIdNotFoundException;
import com.aspsolutions.jframework.standar.JReportUtils;
import com.aspsolutions.jreports.server.JReport;
import com.aspsolutions.jreports.server.PresentationRules;
import com.aspsolutions.jreports.server.QueryLogic;
import com.aspsolutions.jreports.server.presentation.FormatException;
import com.aspsolutions.jreports.server.presentation.ReportEllipse;
import com.aspsolutions.jreports.server.presentation.ReportFieldPresentation;
import com.aspsolutions.jreports.server.presentation.ReportLine;
import com.aspsolutions.jreports.server.presentation.ReportMargin;
import com.aspsolutions.jreports.server.presentation.ReportRectangle;
import com.aspsolutions.jreports.server.presentation.ReportImage;
import com.aspsolutions.jreports.server.presentation.ReportRegion;
import com.aspsolutions.jreports.server.presentation.ReportRepetitiveFrame;
import com.aspsolutions.jreports.server.presentation.ReportSection;
import com.aspsolutions.jreports.server.querylogic.DataLink;
import com.aspsolutions.jreports.server.querylogic.Group;
import com.aspsolutions.jreports.server.querylogic.GroupField;
import com.aspsolutions.jreports.server.querylogic.Query;
import com.aspsolutions.jreports.server.querylogic.querycomponents.FromTables;
import com.aspsolutions.jreports.server.runtime.GroupPointer;
import com.aspsolutions.jreports.server.runtime.JReportRuntime;
import com.aspsolutions.jreports.server.runtime.QueryRecords;
import com.aspsolutions.jreports.server.runtime.ReportField;
import com.aspsolutions.jreports.server.presentation.ReportText;
import com.aspsolutions.jreports.server.presentation.ReportFrame;
import com.aspsolutions.jreports.server.presentation.ReportRoundedRectangle;
import com.aspsolutions.jframework.standar.ASPString;
import com.aspsolutions.jreports.server.querylogic.querycomponents.SelectColumns;
import com.aspsolutions.jreports.server.parameters.ParameterForm;
import com.aspsolutions.jframework.Server.DataFieldDefinition;
import com.aspsolutions.jframework.Server.GraphicsObjectServer;
import javax.swing.FocusManager;
import com.aspsolutions.jframework.standar.ASPMath;
import com.aspsolutions.jframework.Server.RecordGroupServer;
import com.aspsolutions.jframework.Server.HelpListServer;
import com.aspsolutions.jreports.server.presentation.ReportChart;
import com.aspsolutions.jframework.Server.JApplicationServer;
import com.aspsolutions.jframework.standar.ASPConverter;
import com.aspsolutions.jframework.standar.ASPSQLFunctions;
import com.aspsolutions.jframework.Utils.SqlParameter;
import com.aspsolutions.jframework.Exceptions.NoDataFoundException;
import com.aspsolutions.jframework.Exceptions.TooManyRows;
import com.aspsolutions.jframework.Exceptions.NumericOrValueException;
import com.aspsolutions.jframework.srw.SRWProgramAbort;
import com.aspsolutions.jframework.standar.ASPLogicalOperators;
import java.awt.Font;
import com.aspsolutions.jreports.server.LayoutTextVariables;
import com.aspsolutions.jframework.Server.ProcedureCallParameters;
import com.aspsolutions.jframework.standar.Utils;
import com.aspsolutions.jreports.server.presentation.PresentationFormat;
import com.aspsolutions.jreports.server.presentation.Conditions;
import com.aspsolutions.jframework.Server.ColumnSpecifications;
import com.aspsolutions.jreports.server.presentation.ReportButton;
import com.aspsolutions.jreports.server.presentation.PageNumbering;
import com.aspsolutions.jframework.Exceptions.DupValOnIndexException;
import com.aspsolutions.jreports.server.presentation.ReportAnchor;
import com.aspsolutions.jframework.standar.ASPCollection;
import com.aspsolutions.jreports.server.presentation.ChartParameter;
import com.aspsolutions.jreports.server.presentation.ChartColumn;
import static com.aspsolutions.jframework.standar.ASPConverter.*;
import static com.aspsolutions.jframework.standar.ASPLogicalOperators.*;
import static com.aspsolutions.jframework.standar.ASPMath.*;
import static com.aspsolutions.jframework.standar.ASPString.*;
import com.aspsolutions.jframework.standar.ASPAccessFile;
import com.aspsolutions.jframework.srw.SRWRunReportFailure;

public class informeDeVentasPorPeriodo_class1 extends JReportRuntime {
	
	protected QueryLogic queryLogic = new QueryLogic();
	protected Group tempGroup = new Group("GrupoTemporal");
	
	protected Query queryQUERY0 = new Query("QUERY0","MASTER","WHERE VP.MON = VP2.MON AND VP.C_EMP = VP2.C_EMP AND VP.C_EMP = #empresa AND VP.PER_CT = #periodo AND VP2.PER_CT =  ( SUBSTR(#periodo, 1 , 4 ) -  1  )  || SUBSTR(#periodo, 5 , 6 )",null,"ORDER BY VP.MON"," SELECT  VP.MON  MONEDA  ,VP.PER_CT  PERIODO_ACT  ,VP.VENTAS  VENTAS_PRESENTE  ,VP2.PER_CT  PERIODO_PAS  ,VP2.VENTAS  VENTAS_PASADA   FROM VENTA_ALL_PERIODOS VP, VENTA_ALL_PERIODOS VP2  WHERE VP.MON = VP2.MON AND VP.C_EMP = VP2.C_EMP AND VP.C_EMP = #empresa AND VP.PER_CT = #periodo AND VP2.PER_CT =  ( SUBSTR(#periodo, 1 , 4 ) -  1  )  || SUBSTR(#periodo, 5 , 6 )",null);
	protected Group groupGROUP_MONEDA = new Group("GROUP_MONEDA",queryQUERY0,"NONE",null,0);
	protected Group groupGROUP0 = new Group("GROUP0",queryQUERY0,"NONE",null,0);
	protected GroupField groupFieldGROUP0VENTAS_PRESENTE = new GroupField("VENTAS_PRESENTE",2,"java.lang.Integer",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0VENTAS_PASADA = new GroupField("VENTAS_PASADA",4,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0PERIODO_ACT = new GroupField("PERIODO_ACT",1,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP0PERIODO_PAS1 = new GroupField("PERIODO_PAS1",3,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP0,this);
	protected GroupField groupFieldGROUP_MONEDAMONEDA = new GroupField("MONEDA",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"DATABASE",null,false,0,groupGROUP_MONEDA,this);
	protected GroupField groupFieldFormula_columnsPERIODO_PAS = new GroupField("PERIODO_PAS",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","periodo_pas_method","FORMULA",null,false,0,tempGroup,this);
	protected GroupField groupFieldFormula_columnsPERIODO_PRE = new GroupField("PERIODO_PRE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","periodo_pre_method","FORMULA",null,false,0,tempGroup,this);
	protected GroupField groupFieldFormula_columnsMES = new GroupField("MES",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","mes_method","FORMULA",null,false,0,tempGroup,this);
	protected GroupField groupFieldFormula_columnsPORCENTAJE = new GroupField("PORCENTAJE",0,"java.lang.String",null,null,"NONE",null,null,"REPORT","REPORT","porcentaje_method","FORMULA",null,false,0,tempGroup,this);
	protected GroupField groupFieldPlaceholder_columnsLOGO = new GroupField("LOGO",0,"java.lang.String",null,null,"ASC",null,null,"REPORT","REPORT",null,"PLACEHOLDER","Text",false,10,tempGroup,this);
	protected GraphicsObjectServer graphicServergraphicRECTANGLE0 = new GraphicsObjectServer("RECTANGLE0",new Color(135,155,211),new Color(0,0,0),"RECTANGLE",55,270,69,40,false,false,1,0,"Normal",0,0,null,false,null);
	protected GraphicsObjectServer graphicServergraphicRECTANGLE1 = new GraphicsObjectServer("RECTANGLE1",new Color(135,155,211),new Color(0,0,0),"RECTANGLE",94,270,70,102,false,false,1,0,"Normal",0,0,null,false,null);
	protected GraphicsObjectServer graphicServergraphicG_title = new GraphicsObjectServer("G_title",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,164,100,50,false,false,-1,0,null,0,0,new Font("Courier New",1,14),false,"Parámetros del reporte");
	protected GraphicsObjectServer graphicServergraphicG_periodo = new GraphicsObjectServer("G_periodo",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,59,108,148,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"Periodo");
	protected GraphicsObjectServer graphicServergraphicTEXT_GRAPHIC0 = new GraphicsObjectServer("TEXT_GRAPHIC0",new Color(255,255,255),new Color(0,0,0),"TEXT_GRAPHIC",20,59,110,114,false,false,-1,0,null,0,0,new Font("Courier New",0,12),false,"Empresa");
	protected ReportRegion reportRegionHeaderBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionHeaderMargin = new ReportRegion("MARGIN");
	protected ReportRegion reportRegionMainBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionMainMargin = new ReportRegion("MARGIN");
	protected ReportRegion reportRegionTrailerBody = new ReportRegion("BODY");
	protected ReportRegion reportRegionTrailerMargin = new ReportRegion("MARGIN");
	protected ReportMargin reportMarginHeader = new ReportMargin(70,34,34,70);
	protected ReportSection reportSectionHeader = new ReportSection("HEADER",reportMarginHeader,792,612,reportRegionHeaderBody,reportRegionHeaderMargin,"Portrait");
	protected ReportMargin reportMarginMain = new ReportMargin(71,30,38,69);
	protected ReportSection reportSectionMain = new ReportSection("MAIN",reportMarginMain,792,612,reportRegionMainBody,reportRegionMainMargin,"Portrait");
	protected ReportMargin reportMarginTrailer = new ReportMargin(70,34,34,70);
	protected ReportSection reportSectionTrailer = new ReportSection("TRAILER",reportMarginTrailer,792,612,reportRegionTrailerBody,reportRegionTrailerMargin,"Portrait");

	public informeDeVentasPorPeriodo_class1() throws Exception {
		super();
	}
}