package com.aspsols.cotizaciones.reportes;

import java.awt.Font;
import  java.util.Map;
import java.util.Vector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import java.util.Iterator;
import java.util.Hashtable;
import com.aspsolutions.jdbc.ObjectType;
import com.aspsolutions.jframework.Exceptions.RecordIdNotFoundException;
import com.aspsolutions.jframework.standar.JReportUtils;
import com.aspsolutions.jreports.server.JReport;
import com.aspsolutions.jreports.server.PresentationRules;
import com.aspsolutions.jreports.server.QueryLogic;
import com.aspsolutions.jreports.server.presentation.FormatException;
import com.aspsolutions.jreports.server.presentation.ReportEllipse;
import com.aspsolutions.jreports.server.presentation.ReportFieldPresentation;
import com.aspsolutions.jreports.server.presentation.ReportLine;
import com.aspsolutions.jreports.server.presentation.ReportMargin;
import com.aspsolutions.jreports.server.presentation.ReportRectangle;
import com.aspsolutions.jreports.server.presentation.ReportImage;
import com.aspsolutions.jreports.server.presentation.ReportRegion;
import com.aspsolutions.jreports.server.presentation.ReportRepetitiveFrame;
import com.aspsolutions.jreports.server.presentation.ReportSection;
import com.aspsolutions.jreports.server.querylogic.DataLink;
import com.aspsolutions.jreports.server.querylogic.Group;
import com.aspsolutions.jreports.server.querylogic.GroupField;
import com.aspsolutions.jreports.server.querylogic.Query;
import com.aspsolutions.jreports.server.querylogic.querycomponents.FromTables;
import com.aspsolutions.jreports.server.runtime.GroupPointer;
import com.aspsolutions.jreports.server.runtime.JReportRuntime;
import com.aspsolutions.jreports.server.runtime.QueryRecords;
import com.aspsolutions.jreports.server.runtime.ReportField;
import com.aspsolutions.jreports.server.presentation.ReportText;
import com.aspsolutions.jreports.server.presentation.ReportFrame;
import com.aspsolutions.jreports.server.presentation.ReportRoundedRectangle;
import com.aspsolutions.jframework.standar.ASPString;
import com.aspsolutions.jreports.server.querylogic.querycomponents.SelectColumns;
import com.aspsolutions.jreports.server.parameters.ParameterForm;
import com.aspsolutions.jframework.Server.DataFieldDefinition;
import com.aspsolutions.jframework.Server.GraphicsObjectServer;
import javax.swing.FocusManager;
import com.aspsolutions.jframework.standar.ASPMath;
import com.aspsolutions.jframework.Server.RecordGroupServer;
import com.aspsolutions.jframework.Server.HelpListServer;
import com.aspsolutions.jreports.server.presentation.ReportChart;
import com.aspsolutions.jframework.Server.JApplicationServer;
import com.aspsolutions.jframework.standar.ASPConverter;
import com.aspsolutions.jframework.standar.ASPSQLFunctions;
import com.aspsolutions.jframework.Utils.SqlParameter;
import com.aspsolutions.jframework.Exceptions.NoDataFoundException;
import com.aspsolutions.jframework.Exceptions.TooManyRows;
import com.aspsolutions.jframework.Exceptions.NumericOrValueException;
import com.aspsolutions.jframework.srw.SRWProgramAbort;
import com.aspsolutions.jframework.standar.ASPLogicalOperators;
import java.awt.Font;
import com.aspsolutions.jreports.server.LayoutTextVariables;
import com.aspsolutions.jframework.Server.ProcedureCallParameters;
import com.aspsolutions.jframework.standar.Utils;
import com.aspsolutions.jreports.server.presentation.PresentationFormat;
import com.aspsolutions.jreports.server.presentation.Conditions;
import com.aspsolutions.jframework.Server.ColumnSpecifications;
import com.aspsolutions.jreports.server.presentation.ReportButton;
import com.aspsolutions.jreports.server.presentation.PageNumbering;
import com.aspsolutions.jframework.Exceptions.DupValOnIndexException;
import com.aspsolutions.jreports.server.presentation.ReportAnchor;
import com.aspsolutions.jframework.standar.ASPCollection;
import com.aspsolutions.jreports.server.presentation.ChartParameter;
import com.aspsolutions.jreports.server.presentation.ChartColumn;
import static com.aspsolutions.jframework.standar.ASPConverter.*;
import static com.aspsolutions.jframework.standar.ASPLogicalOperators.*;
import static com.aspsolutions.jframework.standar.ASPMath.*;
import static com.aspsolutions.jframework.standar.ASPString.*;
import com.aspsolutions.jframework.standar.ASPAccessFile;
import com.aspsolutions.jframework.srw.SRWRunReportFailure;

public class informeDeVentasPorEmpresa_class3 extends informeDeVentasPorEmpresa_class2 {
	protected ReportText reportTextMainBodyText_graphic0 = new ReportText("TEXT_GRAPHIC0",156,16,reportRegionMainBody,4,reportFrameMainBodyFrame0,"Solagro",10,71,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,7),"DEFAULT",false,false,false,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic1 = new ReportText("TEXT_GRAPHIC1",156,6,reportRegionMainBody,5,reportFrameMainBodyFrame0,"Compañia",10,71,new Color(255,255,255),new Color(0,51,153),null,new Font("Arial",0,8),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainBodyText_graphic3 = new ReportText("TEXT_GRAPHIC3",288,6,reportRegionMainBody,6,reportFrameMainBodyFrame0,"%",10,71,new Color(255,255,255),new Color(0,51,153),null,new Font("Arial",0,8),"DEFAULT",false,false,true,false,0,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginTitle = new ReportText("TITLE",402,23,reportRegionMainMargin,0,null,"Informe de ventas por empresa",12,174,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,9),"DEFAULT",false,false,false,false,4,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic2 = new ReportText("TEXT_GRAPHIC2",488,36,reportRegionMainMargin,2,null,"Fecha : ",13,37,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic4 = new ReportText("TEXT_GRAPHIC4",288,7,reportRegionMainMargin,4,null,"SOLAGRO SOLUCIONES AGROINDRUSTRIALES S.A.S.",16,288,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",1,11),"DEFAULT",false,false,false,false,4,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic5 = new ReportText("TEXT_GRAPHIC5",481,54,reportRegionMainMargin,5,null,"Página :",13,41,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportText reportTextMainMarginText_graphic6 = new ReportText("TEXT_GRAPHIC6",543,54,reportRegionMainMargin,6,null,"de",13,13,new Color(0,0,0),new Color(255,255,255),null,new Font("Arial",0,10),"DEFAULT",false,false,false,false,2,"FIXED","FIXED",null,0,-1);
	protected ReportImage reportRectangleMainMarginImage0 = new ReportImage("IMAGE0",34,7,reportRegionMainMargin,3,null,1,new Color(0,0,0),new Color(135,155,211),59,133,"Normal",null,"DEFAULT",false,false,false,null,0);  

	public informeDeVentasPorEmpresa_class3() throws Exception {
		super();
	}
}